"""MLModel file_index and organization default fields added

Revision ID: 004
Revises: 003
Create Date: 2025-06-23 20:08:00.568541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: str | None = '003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_models', sa.Column('file_index', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('organizations', sa.Column('default', sa.Boolean(), nullable=True))

    from sqlalchemy import select, update
    from sqlalchemy.orm import Session

    conn = op.get_bind()
    session = Session(bind=conn)

    result = session.execute(text("""
        SELECT DISTINCT ON (om.user_id) om.organization_id
        FROM organization_members om
        WHERE om.role = 'owner'
        ORDER BY om.user_id, om.organization_id ASC
    """)).scalars().all()

    if result:
        session.execute(
            sa.text('UPDATE organizations SET "default" = TRUE WHERE id = ANY(:ids)')
            .bindparams(sa.bindparam("ids", type_=postgresql.ARRAY(sa.Integer))),
            {"ids": result},
        )
        session.commit()

    session.execute(text('UPDATE organizations SET "default" = FALSE WHERE "default" IS NULL'))

    op.alter_column('organizations', 'default', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'default')
    op.drop_column('ml_models', 'file_index')
    # ### end Alembic commands ###
