#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "pydoc-markdown>=4.8.0,<5.0.0",
# ]
# ///
"""
Regenerate the reference docs for both Python SDKs.

Run with: uv run generate_docs.py

The rendering pipeline lives in sdk_docs_generate.py; this file only says what
to render: for each SDK, the input package root, the output docs folder, and
the module -> page mapping. Page paths mirror the autogenerated Docusaurus
sidebars, so a module's page path is its place in the sidebar. Docusaurus
ignores files starting with "_", which is why private modules such as
`_client` map to explicit page names.
"""

import sys
from dataclasses import dataclass
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPT_DIR))

from sdk_docs_generate import render_module_markdown  # noqa: E402

PROJECT_ROOT = SCRIPT_DIR.parent


@dataclass(frozen=True)
class DocsTarget:
    """One SDK to document: where to import from and where the pages go."""

    label: str
    import_root: Path
    output_dir: Path
    # module path -> page path without extension, relative to output_dir
    modules: dict[str, str]


TARGETS = [
    DocsTarget(
        label="API SDK (luml_api)",
        import_root=PROJECT_ROOT / "sdk" / "python" / "api",
        output_dir=SCRIPT_DIR / "docs" / "api-reference",
        modules={
            "luml_api._client": "client/client",
            "luml_api._exceptions": "client/exceptions",
            "luml_api._types": "resources/types",
            "luml_api.utils.progress": "resources/progress_handler",
            "luml_api.resources.artifacts": "resources/artifacts",
            "luml_api.resources.bucket_secrets": "resources/bucket-secrets",
            "luml_api.resources.collections": "resources/collections",
            "luml_api.resources.deployments": "resources/deployments",
            "luml_api.resources.monitoring": "resources/monitoring",
            "luml_api.resources.orbits": "resources/orbits",
            "luml_api.resources.organizations": "resources/organizations",
            "luml_api.resources.satellites": "resources/satellites",
            "luml_api.resources.tracks": "resources/tracks",
        },
    ),
    DocsTarget(
        label="SDK (luml)",
        import_root=PROJECT_ROOT / "sdk" / "python" / "sdk",
        output_dir=SCRIPT_DIR / "docs" / "sdk",
        modules={
            "luml.artifacts.model": "artifacts/model",
            "luml.llm._client": "llm/client",
            "luml.llm._exceptions": "llm/exceptions",
            "luml.experiments.tracker": "experiments/tracker",
            "luml.experiments.backends.sqlite": "experiments/backends/sqlite",
            "luml.experiments.evaluation.evaluate": "experiments/evaluation/evaluate",
            "luml.experiments.evaluation.types": "experiments/evaluation/types",
            "luml.experiments.evaluation.scorers.builtin.completeness": (
                "experiments/evaluation/completeness"
            ),
            "luml.experiments.evaluation.scorers.builtin.correctness": (
                "experiments/evaluation/correctness"
            ),
            "luml.experiments.evaluation.scorers.builtin.prompt_alignment": (
                "experiments/evaluation/prompt_alignment"
            ),
            "luml.experiments.evaluation.scorers.builtin.relevancy": (
                "experiments/evaluation/relevancy"
            ),
            "luml.experiments.evaluation.scorers.builtin.summarization": (
                "experiments/evaluation/summarization"
            ),
            "luml.integrations.catboost.packaging": "integrations/catboost",
            "luml.integrations.langgraph.packaging": "integrations/langgraph",
            "luml.integrations.lightgbm.packaging": "integrations/lightgbm",
            "luml.integrations.sklearn.packaging": "integrations/sklearn",
            "luml.integrations.xgboost.packaging": "integrations/xgboost",
        },
    ),
]


def generate_target(target: DocsTarget) -> tuple[list[Path], list[str]]:
    """Render every page of one target. Returns (written files, failures)."""
    written: list[Path] = []
    failures: list[str] = []

    print(f"\n[{target.label}]")
    print(f"  input:  {target.import_root}")
    print(f"  output: {target.output_dir}")
    print("-" * 60)

    for module_name, page_path in sorted(target.modules.items()):
        try:
            output = render_module_markdown(target.import_root, module_name)
        except Exception as error:  # noqa: BLE001 — keep rendering the rest
            failures.append(f"{module_name}: {error}")
            print(f"  ✗ {module_name}: {error}")
            continue

        if not output or not output.strip():
            failures.append(f"{module_name}: no documentable content")
            print(f"  ✗ {module_name}: no documentable content")
            continue

        output_file = target.output_dir / f"{page_path}.md"
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text(output)
        written.append(output_file)
        print(f"  ✓ {page_path}.md")

    return written, failures


def main() -> int:
    print("=" * 60)
    print("SDK Documentation Generator")
    print("=" * 60)

    all_written: list[Path] = []
    all_failures: list[str] = []
    for target in TARGETS:
        written, failures = generate_target(target)
        all_written.extend(written)
        all_failures.extend(failures)

    print()
    print("=" * 60)
    print(f"Generated {len(all_written)} documentation file(s)")
    if all_failures:
        print(f"Failed {len(all_failures)}:")
        for failure in all_failures:
            print(f"  - {failure}")
    print("=" * 60)
    return 1 if all_failures else 0


if __name__ == "__main__":
    sys.exit(main())
