name: Backend checks and tests

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies with uv
        working-directory: backend
        run: |
          python -m pip install --upgrade uv
          uv sync --group dev

      - name: Check formatting
        working-directory: backend
        run: |
          uv run ruff format --check dataforce_studio

      - name: Linting
        working-directory: backend
        run: |
          uv run ruff check dataforce_studio

      - name: Type checking
        working-directory: backend
        run: |
          uv run mypy dataforce_studio

      - name: Set up test database service
        run: |
          docker run -d \
            --name test-postgres \
            -e POSTGRES_USER=test_user \
            -e POSTGRES_PASSWORD=test_password \
            -e POSTGRES_DB=df_studio_test \
            -p 5432:5432 \
            postgres:15
          
          timeout 30 bash -c 'until docker exec test-postgres pg_isready -U test_user -d df_studio_test; do sleep 1; done'

      - name: Running tests
        working-directory: backend
        env:
          POSTGRESQL_DSN: postgresql+asyncpg://test_user:test_password@localhost:5432/df_studio_test
          AUTH_SECRET_KEY: test_secret_key_for_ci
          BUCKET_SECRET_KEY: test_bucket_secret_key_for_ci
        run: |
          uv run pytest