name: Build and Deploy Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: docs
        run: npm install

      - name: Build app
        working-directory: docs
        run: npm run build

      - name: Start SSH Agent and add key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSHKEY }}

      - name: Clear Target Directory on Server
        run: ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'sudo rm -rf /var/www/dev-docs.dataforce.studio/*'

      - name: Copy files via rsync
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -p 22" docs/build/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/dev-docs.dataforce.studio

      - name: Restart nginx
        run: ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'sudo systemctl restart nginx'
