name: Build and Deploy Notebooks

on:
  push:
    branches: [ main ]
    paths:
      - 'wasm/jupyter/**'

env:
  REGISTRY: "registry.digitalocean.com/dataforce-registry"
  IMAGE_NAME: "dfs-notebooks"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7} ./wasm/jupyter

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to DigitalOcean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: 22
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA
          script: |
            docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} registry.digitalocean.com
            docker stop $IMAGE_NAME || true
            docker rm $IMAGE_NAME || true
            docker run -d \
              --restart always \
              --name $IMAGE_NAME \
              -p 8001:8000 \
              $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7}
